### ISSUE TITLE
Tap-to-reply: add settings page that allows user to save responses to json

### ISSUE THREAD

**Issue by NoahCothran** [bbevis6196/inspiration_4#10]
### TODO:
- [x] settings icon on app that sends user to settings page
- [x] settings page has input boxes to create/change the 4 response options
- [x] a save button will write the new changes to the .json responses file
- [x] the user is sent back to the app and the new responses are available to be selected

**Comment by NoahCothran** [comment]
- new responses are not being seen when sent back to app
- sometimes the new responses will show up if the page is refreshed several times, or very rarely it will just work
- running it locally, the json file can be seen with the new data when opened with notepad, but visiting the url of the json file does not show the new responses; sometimes refreshing that page will eventually show the new responses

**Comment by NoahCothran** [comment]
I've put in PHP code that prevents caching and js code that is supposed to stop the Back/Forward cache (BFcache). This has not solved the problem.

To make the new responses show up in the main app page, I have to open a new tab with the json url, refresh that page, then refresh the main page.

**Comment by NoahCothran** [comment]
doing a hard refresh will force the page to get the newly saved responses
will try to fix this issue later
